version: '3'

services:
  app:
    build: ./app
    networks:
      - DB
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    networks:
      - DB
    environment:
      - MYSQL_ROOT_PASSWORD=qwerty
    volumes:
      - ./datas:/var/lib/mysql


networks:
 DB: